name: gha2-results

on:
  pull_request:
    branches:
      - branch-2
  push:
    branches:
      - branch-2
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3.5.0

      - uses: actions/setup-java@v3.12.0
        with:
          distribution: 'zulu'
          java-version: '8'

      - name: Set up cache
        uses: actions/cache@v3.3.1
        with:
          path: "${{ github.workspace }}/.m2/repository"
          key: "${{ runner.os }}-path"

      - run: chmod +x mvnw
      - run: bash <(curl -s https://codecov.io/bash)
