name: gha2-results

on:
  pull_request:
    branches:
      - branch-2
  push:
    branches:
      - branch-2
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3.5.0

      - uses: actions/setup-java@v3.12.0
        with:
          distribution: 'zulu'
          java-version: '8'

      - name: Set up cache
        uses: actions/cache@v3.3.1
        with:
          path: "${{ github.workspace }}/.m2/repository"
          key: "${{ runner.os }}-path"

      - run: chmod +x mvnw
      - name: Installing Redis
        run: sudo apt-get install redis-server
      - run: sudo redis-server /etc/redis/redis.conf --port 6379
      - name: Run Maven wrapper for update and installing
        run: ./mvnw -N io.takari:maven:wrapper -Dmaven=3.9.6
      - run: bash <(curl -s https://codecov.io/bash)
