name: gha2-results

on:
  pull_request:
    branches:
      - branch-2
  push:
    branches:
      - branch-2
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3.5.0

      - uses: actions/setup-java@v3.12.0
        with:
          distribution: 'zulu'
          java-version: '8'

        - name: set up jdk 1.8
          with:
            path: ~/.maven-
            key: ${{ runner.os }}-maven-${{ hashfiles(arg) }}
          uses: actions/cache@version
          run:
            bash <(curl -s https://codecov.io/bash)
            ./mvnw -q test
            chmod +x mvnw

macos:
  jdk: openjdk8

